import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';

interface ExportMarkdownBody {
  projectId: string;
}

/**
 * POST /api/export/markdown
 * Export the project as a Markdown document.
 */
export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient();
    const { data: { user }, error: authError } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    const body: ExportMarkdownBody = await request.json();
    const { projectId } = body;

    if (!projectId) {
      return NextResponse.json(
        { error: 'Missing required field: projectId' },
        { status: 400 }
      );
    }

    // Fetch project with all related data
    const { data: project, error: projectError } = await supabase
      .from('projects')
      .select('*')
      .eq('id', projectId)
      .eq('user_id', user.id)
      .single();

    if (projectError || !project) {
      return NextResponse.json(
        { error: 'Project not found' },
        { status: 404 }
      );
    }

    const [
      { data: scenes },
      { data: characters },
    ] = await Promise.all([
      supabase.from('scenes').select('*').eq('project_id', projectId).order('order', { ascending: true }),
      supabase.from('characters').select('*').eq('project_id', projectId),
    ]);

    // Build Markdown document
    const lines: string[] = [];

    lines.push(`# ${project.title ?? 'Storyboard'}`);
    lines.push('');
    lines.push(`> Generated by Kiyoko AI | ${new Date().toLocaleDateString()}`);
    lines.push('');

    const pAny = project as Record<string, unknown>;
    if (pAny.ai_brief) {
      lines.push('## Brief');
      lines.push('');
      lines.push(String(pAny.ai_brief));
      lines.push('');
    }

    lines.push(`- **Style:** ${pAny.style ?? 'Not specified'}`);
    lines.push(`- **Platform:** ${pAny.platform ?? 'Not specified'}`);
    lines.push(`- **Duration:** ${pAny.duration ?? 'Not specified'}s`);
    lines.push('');

    if (characters?.length) {
      lines.push('## Characters');
      lines.push('');
      for (const c of characters as Array<Record<string, unknown>>) {
        lines.push(`### ${c.name}`);
        lines.push(`- **Role:** ${c.role ?? 'N/A'}`);
        if (c.description) lines.push(`- **Description:** ${c.description}`);
        if (c.prompt_snippet) lines.push(`- **Prompt Snippet:** ${c.prompt_snippet}`);
        lines.push('');
      }
    }

    lines.push('## Scenes');
    lines.push('');

    for (const [i, scene] of (scenes ?? []).entries()) {
      const s = scene as Record<string, unknown>;
      lines.push(`### ${s.scene_number ?? `E${i + 1}`}: ${s.title ?? `Scene ${i + 1}`}`);
      lines.push('');
      if (s.description) lines.push(String(s.description));
      lines.push('');
      if (s.image_prompt) {
        lines.push('**Image Prompt:**');
        lines.push(`\`\`\`\n${s.image_prompt}\n\`\`\``);
        lines.push('');
      }
      if (s.video_prompt) {
        lines.push('**Video Prompt:**');
        lines.push(`\`\`\`\n${s.video_prompt}\n\`\`\``);
        lines.push('');
      }
      lines.push('---');
      lines.push('');
    }

    // TODO: Include arc phases and timeline entries

    const markdown = lines.join('\n');

    return new NextResponse(markdown, {
      headers: {
        'Content-Type': 'text/markdown; charset=utf-8',
        'Content-Disposition': `attachment; filename="${(project.title ?? 'storyboard').replace(/[^a-zA-Z0-9]/g, '_')}.md"`,
      },
    });
  } catch (error) {
    console.error('[export/markdown]', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
