import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';

interface ExportHtmlBody {
  projectId: string;
}

/**
 * POST /api/export/html
 * Generate a self-contained HTML file for the storyboard project.
 */
export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient();
    const { data: { user }, error: authError } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    const body: ExportHtmlBody = await request.json();
    const { projectId } = body;

    if (!projectId) {
      return NextResponse.json(
        { error: 'Missing required field: projectId' },
        { status: 400 }
      );
    }

    // Fetch project data
    const { data: project, error: projectError } = await supabase
      .from('projects')
      .select('*')
      .eq('id', projectId)
      .eq('user_id', user.id)
      .single();

    if (projectError || !project) {
      return NextResponse.json(
        { error: 'Project not found' },
        { status: 404 }
      );
    }

    // Fetch related data
    const [
      { data: scenes },
      { data: characters },
    ] = await Promise.all([
      supabase.from('scenes').select('*').eq('project_id', projectId).order('order', { ascending: true }),
      supabase.from('characters').select('*').eq('project_id', projectId),
    ]);

    // TODO: Generate full self-contained HTML with embedded styles and images
    // TODO: Convert image URLs to base64 data URIs for self-containment
    // TODO: Include proper CSS for print and screen display

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${project.title ?? 'Storyboard'} - Kiyoko AI</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 900px; margin: 0 auto; padding: 2rem; color: #1a1a2e; }
    h1 { color: #6C63FF; border-bottom: 2px solid #6C63FF; padding-bottom: 0.5rem; }
    .scene { border: 1px solid #e0e0e0; border-radius: 8px; padding: 1rem; margin: 1rem 0; }
    .scene h3 { margin-top: 0; color: #333; }
    .scene .prompt { background: #f5f5f5; padding: 0.75rem; border-radius: 4px; font-size: 0.9em; }
    .character { display: inline-block; background: #f0f0ff; border-radius: 8px; padding: 0.75rem; margin: 0.5rem; }
    .meta { color: #666; font-size: 0.85em; }
    @media print { body { max-width: 100%; } .scene { break-inside: avoid; } }
  </style>
</head>
<body>
  <h1>${project.title ?? 'Storyboard'}</h1>
  <p class="meta">Created with Kiyoko AI | ${new Date().toLocaleDateString()}</p>
  <p>${(project as Record<string, unknown>).ai_brief ?? ''}</p>

  ${characters?.length ? `
  <h2>Characters</h2>
  <div>${(characters ?? []).map((c: Record<string, unknown>) => `
    <div class="character">
      <strong>${c.name}</strong> - ${c.role}
    </div>`).join('')}
  </div>` : ''}

  <h2>Scenes</h2>
  ${(scenes ?? []).map((s: Record<string, unknown>, i: number) => `
  <div class="scene">
    <h3>${s.scene_number ?? `E${i + 1}`}: ${s.title ?? `Scene ${i + 1}`}</h3>
    <p>${s.description ?? ''}</p>
    ${s.image_prompt ? `<div class="prompt"><strong>Image Prompt:</strong> ${s.image_prompt}</div>` : ''}
  </div>`).join('')}

  <footer class="meta" style="margin-top: 2rem; border-top: 1px solid #e0e0e0; padding-top: 1rem;">
    Generated by Kiyoko AI
  </footer>
</body>
</html>`;

    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html; charset=utf-8',
        'Content-Disposition': `attachment; filename="${(project.title ?? 'storyboard').replace(/[^a-zA-Z0-9]/g, '_')}.html"`,
      },
    });
  } catch (error) {
    console.error('[export/html]', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
